version: "3.1"

services:
  api:
    container_name: sparc-api-dev
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=development
    command: yarn start
    ports:
      - "2000:80"
      - "9222:9222"

  fetch:
    container_name: sparc-fetch-dev
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=development
    command: yarn start:fetch
    ports:
      - "9223:9223"
