version: "3.1"

services:
  api:
    image: sparc-api
    build: ./api
    networks:
      - default
      - api
    depends_on:
      - apidb
    environment:
      - MONGO_URL=mongodb://apidb/

  apidb:
    container_name: sparc-apidb
    image: mongo:3.4
    networks:
      - api
    volumes:
      - apidb-data:/data/db
    expose:
      - "27017"
volumes:
  apidb-data:

networks:
  api:
