version: "3.1"

services:
  api:
    container_name: sparc-api-dev
    volumes:
      - ./api/jwt.key.pub.example:/app/jwt.key.pub
      - ./api:/app
    environment:
      - NODE_ENV=development
    command: yarn start
    ports:
      - "2000:80"
      - "9222:9222"

  auth:
    container_name: sparc-auth-dev
    volumes:
      - ./api/jwt.key.pub.example:/app/jwt.key.pub
      - ./api:/app
    environment:
      - NODE_ENV=development
    command: yarn start:auth
    ports:
      - "2001:80"
      - "9223:9223"

secrets:
  jwt.key:
    file: ./secrets/jwt.key.example
