# Base configuration for docker services

version: "3.1"

services:
  api:
    container_name: sparc-api
    image: sparc-api
    build: ./api
    depends_on:
      - apidb
    environment:
      - MONGO_URL=mongodb://apidb/

  fetch:
    container_name: sparc-fetch
    image: sparc-fetch
    build: ./api
    depends_on:
      - apidb
    environment:
      - MONGO_URL=mongodb://apidb/
    command: [node, fetch.js]

  apidb:
    container_name: sparc-apidb
    image: mongo:3.4
    volumes:
      - apidb-data:/data/db
    expose:
      - "27017"

volumes:
  apidb-data:
