##
# serverless.yml
#
# Copyright (C) 2016  Grinnell AppDev.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
##


# For full config options, check the docs:
#    https://serverless.com/framework/docs/

service: publications
frameworkVersion: "=1.3.0"


globals:
  stage: ${opts:stage, self:provider.stage}
  region: ${opts:region, self:provider.region}

  apiIdsByStageName:
    dev: 14dvrdkbu2
  apiId: ${self:globals.apiIdsByStageName.${self:globals.stage}}
  apiModelsUrl:
    https://apigateway.amazonaws.com/restapis/${self:globals.apiId}/models


provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-west-2

  # forwards compatibility, see
  # https://serverless.com/framework/docs/providers/aws/guide/functions#log-group-resources
  cfLogs: true

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"

  # you can define service wide environment variables here
  # environment:
  #   variable1: value1


# you can add packaging information here
package:
  # include:
  #   - include-me.py
  #   - include-me-dir/**
  exclude:
    - .idea/**
    - .vscode/**
    - test-events/**


functions: ${file(functions/functions.yml)}

resources:
  Resources: ${file(resources/Resources.yml)}
